// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from helloworld.djinni

#include "hello_world.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class HWHelloWorld;

namespace djinni_generated {

class HelloWorld
{
public:
    using CppType = std::shared_ptr<::helloworld::HelloWorld>;
    using CppOptType = std::shared_ptr<::helloworld::HelloWorld>;
    using ObjcType = HWHelloWorld*;

    using Boxed = HelloWorld;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

