// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from helloworld.djinni

#import <Foundation/Foundation.h>
@class HWHelloWorld;


@interface HWHelloWorld : NSObject

+ (nullable HWHelloWorld *)create;

- (nonnull NSString *)getHelloWorld;

- (nonnull NSString *)getName;

- (void)setName:(nonnull NSString *)name;

@end
